quay:
  namespace: quay-enterprise
  component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: false
    - name: mirror
      managed: true
    - name: monitoring
      managed: true
    - name: postgres
      managed: true
    - name: redis
      managed: true
    - name: objectstorage
      managed: true
    - name: route
      managed: true
    - name: tls
      managed: true
    - name: quay
      managed: true
    - name: clairpostgres
      managed: true
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret
  setup:
    admin:
      # Generated password is saved to the 'quay-init-token' secret in the configured namespace
      name: quayadmin
      email: msalowit@redhat.com
    user:
      # Generated password is saved to the 'quay-user' secret in the configured namespace
      # The API only allows the creation of superusers
      name: developer1
      email: msalowit@redhat.com

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

global:
  hub:
    clustername: ocp
    domain: gypsywolf.com

  quay:
    org:
      name: devel
      email: msalowit@redhat.com
    repo: example

clusterGroup:
  name: AUTOMATIC
